from . import help
from . import start
from . import Tarif
from . import ikkinchi_qadamlar
from . import oylik_paket
from . import sms_hizmatlar
from . import internet_hizmat
from . import halqaro_sms_hizmatlar
from . import maxsus_taklif
from . import usel_tarif
from . import usel_boshqa_hizmat
from . import uzmobile_tariflar
from . import mobiuz
from . import echo